/*
 * main fight classes
 */
export class PlayerInfo {
    constructor(
        public playerAccount: string,
        public playerRank: number,
        public creatureTypes: Array<number>,
        public rarityTypes: Array<number>,
        public creatureLevels: Array<number>,
        public creatureTrainLevels: Array<number>,
        public creaturePowerLevels: Array<number>,
        public creatureExp: Array<number>,
    ) { }
}

export class CardStats {
    constructor(
        public maxHealth: number,
        public health: number,
        public damage: number,
        public speed: number,
        public defense: number,
        public magic: number,
    ) { }
}

export class BattleInfo {
    public winnerAccountName: string = '';
    public rankChange: number = 0;
    public expGain: number = 0;
    public player1CardStats: Array<CardStats> = new Array<CardStats>();
    public player2CardStats: Array<CardStats> = new Array<CardStats>();
    public attackerIndexes: Array<number> = new Array<number>();
    public defenderIndexes: Array<number> = new Array<number>();
    public damageDealt: Array<number> = new Array<number>();
    public allyTurn: Array<boolean> = new Array<boolean>();

    constructor(
        public playerInfo1: PlayerInfo,
        public playerInfo2: PlayerInfo,
    ) { }
}

export const ElementMatrix: number[/*attack*/][/*defense*/] = [
//                  Pet     Onyx    Fire    Water   Electric    Ghost   Plant   Psychic     Sand
/*Pet*/         [   1,      1.5,    1,      1,      1,          .5,     1,      1.5,        1   ],
/*Onyx*/        [   .5,     1,      .5,     1.5,    1.5,        .5,     1.5,    .5,         1.5 ],
/*Fire*/        [   2,      .5,     1,      .5,     1,          1,      2,      1,          .5  ],
/*Water*/       [   1,      .5,     2,      1,      .5,         1,      .5,     1,          2   ],
/*Electric*/    [   1.5,    1.5,    1,      2,      .5,         1.5,    .5,     1,          .5  ],
/*Ghost*/       [   1.5,    1.5,    1,      1,      1,          .5,     1,      1.5,        1   ],
/*Plant*/       [   1,      .5,     .5,     1.5,    1.5,        1,      .5,     2,          .5  ],
/*Psychic*/     [   .5,     1.5,    1,      1,      1,          2,      1,      .5,         1   ],
/*Sand*/        [   1,      .5,     1.5,    .5,     1.5,        1,      1.5,    1,          1   ],
]

/*
 * bot names
 */
export const BotNames: string[] = [
    "Deatomannryu", "Foxysbranjo", "kiankrondep", "CoCaaulo", "felichbeoxBr", "Goldenkirf", "happawkb", "kiniwitc", "Maalov", "Le Olzor", "Ziemuradeaky", "OneNubbe", "Joaonspe", "MrJaierrabbe", "LinkudaCypeh",
    "TomCilol", "GenGrind", "fattouzy", "MrLundenser", "ItsNunny", "Eggbaalmo So", "Zafiarco", "Quacanda", "IroHanti", "Jacoen Cudly", "Prinhinu", "Hannad", "Zsologap", "Kinghe P", "Bushimuy",
    "Ashlemli", "Puffarry", "nekoruna", "niqqhefarry", "Bambavom", "Georeoma", "Ametonce", "ne gagal", "jumpeowuizkl", "alanpeci", "Ianusdowy", "PanielipiAka", "CapsroflZARU", "Gaitalha", "Koseeh",
    "Ridauanr", "oranlyin", "NuaDstwaltze", "romaruce", "Deiveona", "Cecyracjorl", "comaheliradi", "AK Nafia", "Fawwrky", "Jappfoxy", "Karantis", "Fagalacktric", "Utkooloe Do", "Alteinsl", "etozarkSies",
    "sosiouft", "WykohatGeenC", "Jereathaxan", "realusti", "Brinroba", "AlmaUCK ltan", "jacqmir", "KOOLsiwdener", "benzndre", "Bitculiuvhlo", "WindergeiLTa", "SmilALIN", "A FalueWquez", "Ueslmarg", "Umbrezihvero",
    "pipe Fan", "arkaapezlbas", "Jumpazujadma", "rossjinnkylo", "Cloujgamntas", "ryoszaac", "Gabeaxim", "Genelavi", "Meduxper", "CdaMsuan", "Shujn SinPan", "SHADathi", "Androxel", "Pheoizim", "GANDucky",
    "Onindivatoli", "ryananal", "Avalragoerer", "emadlMaZ", "Wakeobzlt", "ham utis", "Laviropeicsw", "Leniinot", "Lilaucadacle", "Jackpple", "ohthoxarltas", "Bobszure", "Jumphostniel", "LeFracob", "SuPeolfimbid",
    "Iluhoob", "edisezmo", "Oniwugog", "Contariusher", "Ateubbua e", "Noahathe", "SerMectoeon", "torosycM", "icalzyBumir", "kidgiankidic", "gamipic", "Robooror", "ElPoinkokach", "Papaenis", "Maizobinha",
    "Pedroisothan", "Marccyyyka", "Unluhinopane", "poishomagaKu", "jamahangCI", "CARAamor", "Exevourk", "jameovaTllye", "tuflallatinh", "The awii", "mlodherasice", "KobiatOf", "Rubekari", "vovaar R", "Ricooul",
    "nsboilFrlist", "EFISerocrtal", "Karmldo", "Lewiarko", "Moocapeu", "Bennuckl", "Tankpplettyz", "Alonradelopi", "Dylaarrckame", "cadene Berry", "KanioocheSpo", "Crutodhiinoa", "Oasiexe", "Catclentndri", "Supeheid",
    "Gabrallo", "Adruybee", "MimorimRlexa", "Lynatall", "Adamukun", "Carooker", "Emptanty", "Skooacke NIEL", "MaltineSnisr", "LianDare", "Brufoice", "Daneopplcife", "Ibisirecird", "EL Fonkulas", "MortrTin",
    "Tor amiptic", "minecnod", "StarheAnixes", "Kappbsum", "A L kam", "Alisnimakohe", "TheCOOLYrosa", "gianhoco", "Gustmigr", "akayucky", "MA nut", "BotartesakNo", "WPG egitozy", "Kikakowlikt", "Dogecy Nam",
    "Niloikto", "AngeaceT", "Cybaain", "fabiinst", "humureshgJun", "Kamuohirubb", "Woffkiap", "VISEaena", "Vortan W", "Shazndo", "JacoostIaLom", "Amuqjvenliso", "FiLLenta", "Gustigri", "milebann",
    "Etnascarpple", "YBFF Ran", "Pracsdoieas", "UrMaarcoreit", "Azalydraint", "CaptXOLE", "bitbrokolton", "Kingiltr", "Vaganfikster", "SirRfter", "evilANY", "Lavaishoce", "volbostC", "Trozodaptai", "blazucif",
    "Forkcareasma", "Elbandia", "Burulext", "Midigly adi", "Soutmegaspie", "Kseralke", "lkohoby iake", "Jaefavvaumin", "oso edne", "AbriaBR", "blokvont", "exemenouito", "mostcyyykow", "Ekisillo", "RaylaxLilate",
    "orcuezbagasu", "Milduxus", "Alejdriaegos", "Xeroshidckpo", "NoNauy", "Blueogueyman", "axeleamFy Gu", "Zorpnivemory", "Hufeycoopeli", "Kyjiedox", "ganjuzke", "Roshkkampusd", "Ugetayma", "Xiahedlo", "Melvaysobero",
    "Mystssas", "Acidiogonath", "SaburSebhino", "macaatsusude", "Draksgei", "Zipptoolilig", "nomkuseyrvii", "Gaberomd", "AcoIicol", "Raytmerithur", "Crabiangiapa", "Gkoji", "asheorle", "Actsornoco", "politiennnna",
    "Winnl Bi", "seammilk", "Evililia", "Raptulki", "Kyzoord", "Eldice A", "Sparelin", "RoryringZARU", "adiaLIPS", "FirezOh", "Apolisen", "cypserer", "loriyukud So", "RayDerst", "plouhthe",
    "shukeepatret", "derkarryJeff", "karoatOfllpa", "ThRoeeka", "Koohtim", "Pan appy", "NerdFIN", "aspiores", "RedBhado", "drajobycate", "diegodia", "iGoouck", "Chefiendavit", "krys", "Nazhctog",
    "Jeff Krso", "SirWergebada", "Sephtennlian", "Rookions", "Azuranah", "Rodnedredut", "Vakoegishio", "Yajmeral", "Usuuemeb", "Heavwink", "Jimbinja", "Khilen", "Trolaba", "Nazhonst", "Nikkavin",
    "ArchDEMON", "Darkhave", "Tombakar", "Arieavenluna", "Azulevradara", "Claue bonkDi", "Avezl Hu", "AzkaameKrone", "Grayucchmbin", "aspiobal", "feargapasain", "Caiohe", "notrheCr", "Pinknvismcun", "Jaydppop",
    "JEAN", "Faurar", "HaaCacre", "Heinohn", "Elizuroi", "Sturung adde", "Khilxilo", "Ninjose eGre", "Deasocko", "Gullolhk", "Hercistepes", "Goldffpe", "Acaduckamevi", "Bacorman", "yoelnne",
    "denimuis", "NixIweez", "Raptellama", "Overlakkza", "Crooehrmdman", "matyoize", "Chleuyuk", "gunzaxas", "lukel Mu", "Equiherbmcat", "Billegad", "Nameomeocash", "Leksokok", "Demoatre", "Anonalf",
    "omegrava", "rodgkottred", "Tomiatarder", "Bennislechan", "Morseyon", "Liamaspozjon", "artmane", "Freedika", "Smilangi", "TheMrsan", "Lovlome", "MooseroXmon", "Kinyurdeolf", "Veyrordn", "Kasaantsiesi",
    "eepoogo", "Primceshnta", "Timolain", "Efmidmir", "Contotieesme", "Rapnanil", "EskaandeexSe", "Antewaprgio", "Reflanda", "Drawaitmtoma", "Goodceptacta", "Vanhilan", "SamuartebSon", "LIFEeroc", "loroanie",
    "Butmowel", "Keropina", "Terrpiko", "BalbinsW", "Izgeeros", "Guroenny", "Riccpect", "Maisirileent", "soulbeli Da", "Lurvhe Shi", "Lucaadarhann", "fazeeass", "Skyrrkan", "boopheon", "Jupieads",
    "Geray", "Likuaionsgar", "Kamilexa", "georacon", "enkiiste", "andeoellkas", "Piporeenrbar", "webbeerautto", "metaigmurae", "vlashang", "Adolrait", "Alfiestrlikt", "Sorilvar", "Lautldos", "drubevyamor",
    "SouUuria", "firewitoen", "YISU", "CerbVinilufe", "leonrosephea", "Vaniizhuyum", "kiriacieanel", "Natuavpsklo", "CasaGYP", "viakgaLaeloz", "madelysi", "PapirMeto", "Nighytnt", "Yourherohnka", "Doggiragiron",
    "SanglanDhnaw", "JackamerdTop", "DunnopilNono", "Yapsaaew", "NaleSKAR", "Raveliss", "yellucky", "sethiberrisc", "Luiztto", "Johnzali", "Obamztjanhbe", "Snaknkle", "zergatst", "Muhtrtar", "RautyteBanks",
    "Atzmomnustav", "nextajni", "grilmopo", "AiseARGATomo", "Arclargo", "NebuTGR", "Enyaharprler", "demeuspere", "Cronrato", "madmaryM", "allamegaanks", "Oninorth", "xXJaoveadow", "sofinabe", "Soraalru",
    "Ovidikru", "Alphllah", "bounenny", "AdamebaOvis", "Kartiffa", "landcerindo", "Guccabad", "xkimivel", "EsSsgoreltre", "Kungxpos", "Pedritte", "Hopefmetolf", "tarammaumeFa", "CandeFixny", "Fallabactic",
    "bontagarionl", "Ohamorotsy", "rentngin", "Hyukllid", "Merlesqundra", "Traileme", "aniarthu", "MarvukuO", "Dartuzuremi", "MankerryLEL", "mvaladCa", "Hridaidu", "Admiohan", "Auurendo", "Xgdan",
    "julikrosncen", "Propilgo", "supeerbe", "Fealonge", "jlaueng", "Danduduf", "Skymbelenki", "Holyuliu", "Starait", "Deivorpenicz", "AKA Taeda", "putuzanrama", "Sir uovo", "Ammyhoenname", "andrexte",
    "Magnaedaevil", "Bereupperten", "mkotuanazytr", "Breaalilody", "erechonazol", "snowentlabga", "llaingietmat", "Ahmeorenunto", "ItsAlantheu", "drophotoray", "punkuinsexei", "oxfonich", "SirpackM", "Cardorstlfyr", "Rafaoose",
    "davierka", "MoToon", "Von abbebreo", "GabiPand", "Eevenubi", "Yoriathpmonc", "Lennhiliotik", "Whitreatsus", "Bottlycapai", "entoquin", "Noobrewa", "Takoachn", "OnixyesO", "Markallmdrew", "Nudiotere By",
    "SukiirJo", "hexedriaingo", "Overuukivaro", "Drevlexa", "Burgarkiri", "Meriuliorly", "Yisuikit", "Colmyder", "MOMO", "Thicayrotlin", "sakaLIOD", "Dangavenbmor", "StarnreiLUCK", "ZenDriff", "TheNmpGuatox",
    "Powee", "brasasar", "KarooltveK", "AusxoRay", "rickabal", "Bort", "MAKA", "karsin", "sadulect", "smallREST", "valkrablexro", "Eggbelab", "Avilerem", "LordroBouavh", "Jerevale",
    "turtuzzy", "crooazel", "Antridga", "Heromaowond", "Assaasa", "Infianty", "Samorisccaj", "TioJelde", "chilripl", "jakslexu", "Kachuma", "Majoilba", "Muncaxga", "Animabloraut", "haadon",
    "IceSagne", "allapuntris", "Pingalleubak", "Il Seffe", "Birbamuiral", "Failemar", "Siriuck cobb", "jakortiorkes", "Spyrdora", "Yuriazim", "koltubbareo", "Saimrinckoo", "Cualhoma", "Cruorwinrtuz", "Ponaapso",
    "Hellidi", "Darkityqe", "Connicco", "Owarrue", "Matrlimiunte", "Mnveablougu", "Alijarri", "kenjrion", "Balaaleb", "Adusubbl", "Deatmner", "Denaorte", "Rajnayoizli", "Mietusti", "borbuigi",
    "AshTeygncle", "JautinchnTsu", "salaunda", "octolivii", "Julihyca", "Jadeermi", "Svenyukeas", "Bumbapu", "Warmungmanal", "Eevearra", "leanaxim", "Andrrugu", "XornaraZark", "Einslex", "Crisreepnato",
    "daniinsl", "yagoodiallia", "Burgapta", "jcoravin", "Wodzaniegic", "Flamscarfear", "TemmogYe", "Decrelys", "Dratddarbosi", "Angeikku", "flesuaki", "alexonebazy", "MacRapph", "anluoomkyo", "Vinzuyth",
    "Tairosiskima", "Blannfec", "DocSpeed", "ToSaeult", "arteerobuanz", "Statdikl", "Pikahili", "kickitch", "Toaseylotima", "Arnoold", "Ozzyisse", "Yololone", "Robetali", "Skycumekncen", "Hellisamdalk",
    "Oudeobidnpav", "Levubyss", "BazyHARK", "CrocorDT", "justxelp", "juliasy", "Pitenton", "Unifenti", "Wouteobap", "Johnung", "Jamieoar", "ALANambo", "Zoniord", "harpevilezna", "AceKyan",
    "Unhoyhi bez", "Piandobe", "Hammeddi", "Unclucky", "UganRYP", "Artho", "jeremphi", "Aripozza", "Lilieygi", "Vagahaz", "Psycl So", "EpiCanty", "AlexmRev", "Clauabriache", "Saskirusrox",
    "TangX", "Martilda", "Derparba", "The taye", "Cocaemacros", "bitsLove", "VaysllanvinD", "Maycrins", "Kaszutdaikes", "Docsnake", "Scuregab", "One dam zer", "KS Loitz", "Veririn", "brunoBalstei",
    "Red leCougar", "grusaddo", "Nathank", "Luxa", "Limeazim", "MrErnuse", "beefmojito", "Jereolo", "Althami", "Offiailotche", "Battabloeply", "Cokienguisty", "Diomhase", "Pizzenpa", "Potaidki",
    "Mirnorualdi", "Lennel", "TheLhavy", "Holyrazytron", "edritefarvey", "alvierob", "netaazujulel", "nampeithpria", "Creedriani J", "Mordners", "Secubaaewaa", "Inviisteivdy", "Javoocieayko", "Skitmanoy", "wenakana",
    "Lokenen", "Warimlet", "GenGrthu", "duduff", "eyesenwi", "ENOTodes", "EL Gucad", "pkarevee", "wixperil", "dzhoalfmeru", "CykarumB", "LoyainkMclit", "Raugomplt Bo", "Iasfreenboom", "derk Bug",
    "HansARAM", "pepel Chycho", "whoshail", "Crusuntemsin", "danpuanichol", "Fallost", "Garrorksrito", "Why igeranan", "EinsatyrnHav", "lentreemvidC", "animuppeavit", "Polaatovrael", "Demouuh", "Kadascar", "diogringbian",
    "bronalocka", "Pureumasrice", "Patrordo", "snoorich", "Midgunt", "gael hatuna", "Sylaome", "idathingen", "FNAFzaze", "Awakaari", "AlexinessT", "Ullyechb", "Derpinaritad", "Balomamige", "Detenthorolk",
    "allacarrphil", "Havocoob", "Risusledss p", "BigMbyssegri", "Nicoompi", "klimatorphil", "Zeroenpamfa", "xAviagradrew", "Forele D", "popa am rria", "moinaczk", "Adolafhi", "Omegzuko", "HumbaKaR", "Bob pivage",
    "Adefur", "antooz", "ziliostenic", "NotSooki", "Zonnustinrei", "DocSawon", "genungus", "Weebreenndan", "Huntostm", "GOD ppleilTh", "AdolonKa", "Piraerosidom", "lyrichihrERE", "Johnnifi", "Gamepikeinix",
    "FionheMollis", "erdanoki", "dotzthun", "God edro", "ivleacke", "JeriealPstle", "Diogandaadow", "Willilip", "LokyipFavine", "EngueowP", "afroreve", "MONSagiu", "Wissentuli", "Akroamie", "Yuvaolor",
    "Arwelexahish", "Aslaxych", "martordi", "Juddie", "CrokunYdxapo", "EBOO", "AdamuliaASEK", "Peruero", "El Harec", "Dudembeuer", "Psyclcob", "Oudesh K", "BruxuadaRALD", "Vinistro", "Reapepa",
    "Xileroximash", "Nosiliapsmic", "Enjou", "kitaonar", "OSSYmanolo", "Enaireemempl", "JonntheK", "Von egat", "ShakhishLLY", "Kenningeenn", "Scarsenbgotz", "astrticklaga", "Leylikanobro", "Natsrind", "zbusabbe",
    "Legirosieric", "alexvendrowa", "sadoanyipex", "Slaylmugrat", "Zalaumboltsu", "Nawiaudde Pu", "Kibeirae", "MarJatHizer", "Mr Tussy", "El CGood", "Foreeat", "GetBenakeen", "Bennafarng F", "Daleutte", "Kaluolid",
    "marizkaiozha", "razourdeNERA", "Magibdal", "mokailsz", "Niclenat", "Beanoleo", "Daaruist", "Ganducky", "Balta dijewo", "Tortwipe", "Luweinar", "Sergendontim", "AgituhuL", "therlasmmiot", "Mineries",
    "EartlowCmina", "Huhmardw", "LovaunkAnn", "Deltasta", "Toasijammpai", "Mattonra", "maajroontsuk", "sammass", "Edivalov", "Odkreyekgrat", "Scarrpad", "Readnule", "DrawiegouCar", "Raspnich", "binaneK",
    "Prinario", "lyrircaX Di", "whathatG", "Viktrups", "Vala a agust", "sticuphe", "Bezlinkl", "mostose uper", "The leinhark", "Archenda", "GeveukitxelS", "LeBrnti", "Vasttew", "Gameufuseku", "Sad xcel",
    "Lenialat", "Frosiano", "Erasalag", "SrToansedigi", "Propeanf", "Mayoalke", "Brouillu", "alexrienze L", "bontinglzal", "Atlakurcjoss", "Hugoyrge", "Nirioits", "DaisXkot", "KotheeJa", "Miniredo",
    "Doorackliden", "Dexteine", "joaoiruzbba", "Mitiinorgerh", "TeGeobalrisB", "Dangorvm", "xOpringr", "Aeroengu", "PolaotmAench", "Dirmetuk", "Mataobrarmes", "iijmasuklu", "ipadwelogram", "Ixyrnjoydiel", "Anubitor",
    "Sargerk athv", "Loilenisast", "Trisabeg", "Cyprolve", "TheCdamb", "luxteban", "Joreonna", "AnotarkHBard", "Distharlrry", "Haizombi", "Uchieniammel", "On Mnicarion", "Clymimmi", "ElRoorug", "allaexullan",
    "Senaatabred", "Nikkaizert", "Fisuoukaenni", "Alalathu", "mdisltra", "unknocko", "roinoly tman", "andeutek", "Athuobylls", "Indeiggy", "Banaeusl", "currruls", "Guizusti", "NlOL", "Kirawi",
    "Nabeaniu", "vinialetlwak", "Alexl Du", "Souvrrlarah", "Majathia", "Omegunat", "noobildr", "Filisuan", "Killeveenryu", "iconrtemlish", "Denmoltockan", "ExhaDeni", "orizrlav", "Acetatsu", "ASDFruna",
    "RyukameKekie", "kenhodri", "Pedoonnyutik", "santhaki", "Gooblapmtdem", "mateumar", "infoillo", "Puppssak", "miepccab", "Twisiunis", "Framoon", "Mikihoenweli", "Mortrata", "Scamroopchar", "Evilen W",
    "Escotibb", "HandedBa", "Hitmucky", "keeparrotten", "joseaumc", "Zakkujic", "maridruxti", "xbedashe", "whosapsteDuk", "bugsira", "HUNTudZioom", "Alexirro", "InviheRadrig", "Decezata", "Abudldtiiasb",
    "estaabba", "marsrifopphi", "grifhoencas", "Roseandg", "Dogeick dyba", "blazringdrig", "jellrabe", "andiluedmyl", "DirtTree", "Volbeni", "Supeunhi", "singentl", "Ximxmpir", "loteyBaJante", "Blitvori",
    "smigpud", "Baborcus", "DavinlucpNud", "Possarryead", "Omnerunogo", "Adamlan lin", "gamiaesenzil", "semaodmerneq", "Reibuki", "WeeaUSO", "Sonnen C", "RickheBaadi", "Bad URB Yoddy", "TheBuruz", "xenotopi",
    "La MECH lbex", "Grauahim", "Baueabad", "Miandonc", "WIDO", "Inquiburjicd", "Szatossallo", "Eizerkim", "damoizzodori", "Mazeere ruze", "kingilve", "alixfan", "GOLDnafu", "Suzyulia", "Hugoarba",
    "Assaliteonso", "Nanaiego", "Asiaothe", "gabrikasis", "RobooqMa", "Conafmetshax", "Oksonigm", "Safairty", "Blacathi", "Eziroast", "EffeaGna", "androshi", "avawranc", "TheMedlo", "Cheekarigodi",
    "isaainka", "TonDassa", "biozekoSUSS", "Gatoeezn", "theaicol", "Mojsesci", "SimGiinm", "Malcaip", "ArcOalai", "Achiconobot", "Patricol", "Perirekm", "Tonplvi", "Houn P Etach", "Alexlyae st",
    "Septlijanice", "AICAdiscang", "Wandaibt", "Marcasteilia", "AchiAtepotik", "icepever", "Ivanojal", "KempameX", "Rattevoreric", "pandnicotLaw", "xobaorefnito", "Reapeosordur", "Chotukioda", "mynaoros", "Kiddabri",
    "Kandyzylig", "Tuomayth", "Lanclexatect", "Shisciga", "TheJaiginaBa", "Pescrob", "Bizaight", "Heinalgr", "GeeGpang", "Kinkenpannar", "NEAMheoneZea", "Killlake", "Maxiystirma", "Ampihebi", "Ticoigorzio",
    "codelaus", "eartercu", "PaccridSessi", "Frededho", "Snakgametnoo", "Mizhsrae", "KevNoloM", "wissenurlind", "Altaump", "bogdongwhone", "Righopra", "quinuite", "Arkkrtur", "trivung rive", "Raptgor",
    "GeneRVAT", "Akkasa", "Dikrenri", "canoaibt", "Lazyart", "pinaadHazzy", "DJLiulia", "alpeumusjki", "Jackhyca", "Ghosshul", "someumquxblu", "Natehant", "aweslixxanki", "ilkounne", "Zorearrozysb",
    "grunon Ifia", "Mattichasolo", "YunoPtii", "Ciemnimoerz", "Bossemip", "Mediauckuble", "endlvent", "Yusuainbndro", "benlod pnim", "anthmopo", "Cencenverk", "MagAecodefan", "CanYoaodrdof", "MasoosunFro", "Kinghe Swoke",
    "All obby", "Poke HAV", "dabolare", "Macseohaisto", "Kandhunnbes", "NibbinTs", "SageNANA", "shinssasienn", "rainragogcen", "AhruERP", "Cybenion", "Toufozzy", "Extrendr", "Imuni peruda", "Starombrxie",
    "mwsastrotoll", "SilvirWe", "FoxiossS", "okanndno", "elmasluiperi", "IamJyBr", "Ichbapamsine", "obozhmed", "Arnoelax", "sumaasteton", "Namialukeek", "Heror Juevge", "ZeroustaGRY", "Onurlendtour", "eparunarzhou",
    "Alucs Ezerin", "DuderencksA", "Ysgruukithur", "Captungm", "thorkunk", "morendynrkis", "SouldwinMING", "DRAG P", "Darkinglrdon", "alasokermaku", "Lucaber", "danyl Smumcr", "Lukeanek", "GabranyX", "allaeoszrcy",
    "MeLiaroc", "OneAbsol", "arasells", "Estehimp", "Lumil", "Yankolfioden", "Adrihikr", "Sileakas", "Blaclocklanb", "Madaoppeple", "Ryneinus", "Osameli", "Akeyonto", "Edenkhy", "Aryaylor",
    "Burgeiff", "Arigrtar", "Argaathp", "Amikando", "Homeerbeu Kn", "Arifildaex", "Senyalkeguii", "paraaleb", "Ericuizgald", "Boraende", "CoCooldemori", "Flammopo", "MockuBobria", "Morsarry", "Viloemin",
    "Damfiknode", "WarTauef", "Rahja disafo", "LuscHICC", "Yangank", "Taurdreyvanp", "Wolfesee", "almieini", "Flassaacckki", "Feliouth", "Orelirvi", "loceheVa", "wissuyah", "Eskeeril", "Trifolan",
    "Atlailkmldri", "PakiheLa", "koziutisneh", "gnompace", "Royargon", "BeaigAt", "tomiaayd", "RuBiess", "Jerehe", "justtoolrcos", "olivajihkis", "Braiakus", "Decoord", "Deidandogo", "johntim",
    "noahlliampli", "Mineidra", "Hausucho", "yminuck", "glitntim", "Meahar", "Ionaay Ntes", "BRUM", "Marlisca", "zielrunganan", "SenzidiProco", "atteobzsqui", "mocduper", "Yuraystl", "yeriatsunati",
    "rafanrearday", "LetuordbACE", "Miravika", "Blipukitdrew", "dovaegam", "Carnasikpret", "edu end", "IronanFrte", "Evilafaviral", "Skotuice", "hinalimp", "Xerobochnkor", "Lianbliv", "illiakrehate", "Duraieff",
    "Unifrago", "Belladakcher", "badcakis", "anthavid", "An Alucaeric", "DismDyen", "CritrSeb", "Alexapuc", "Cybrargecirc", "Okruannnk Se", "Pitearom", "Nicoanadexro", "arieomastros", "Rockhlebobnu", "kazir",
    "origick", "Jueckoform", "Goodlzorpane", "Vectoolggius", "Admaunni", "Sorearts", "volbwadsters", "quteolorkvei", "TeldipZblanc", "NoromZle", "menoolsphley", "mikaaste", "jaceerryptio", "Valirgonltam", "insaasakkas",
    "Easoikainva", "Tonilter", "War reveahtw", "etozabbindia", "kiariddr", "Supeugre", "Yhorreja", "attougo", "Teraanek", "IceCsych", "Rorkkakwan", "OmegdivaseMo", "Medilexi", "Watceben", "beel The",
    "paulaBigro A", "barrohnnedim", "Ethearn", "LaTriadjoxs", "andrubpa", "AlfiadamyRed", "Eckaompaoctu", "Dannholi", "collvangitzl", "Stenzyla", "Gonkgnitlais", "Daarncle", "MidgLmi", "Aviluendoo", "Mozoilsomotu",
    "Deoshori", "airberdGkinh", "Mastrackanaj", "AlyDuccionDr", "badmenocckom", "adamabiz", "Pzeuiksxinro", "Glauickbti", "mateLeondura", "floxenne", "drewl Seuty", "Mirrhatl", "Primalsenz", "achulueO", "Cappidra",
    "Luizeste", "Dimmobor", "Remzimbi", "Ludeatan", "Deattarkedud", "BlacuxartCat", "Nanaruthps", "greiidne", "Orl", "Danteedlt", "Tanksych", "Sir eddHtist", "Sharoon", "Ropiamd", "sinsegan",
    "Wakeon", "pype", "Rodono", "Andrakiter", "Unicil", "MANA yes", "Kynekiss", "Trueir", "jonbkaiz", "Monika", "IviceAreke", "Busienav", "LaLiateu", "Xelaion", "Manyighozmul",
    "Swiriaraursa", "Darkeoga Lek", "itzLaeng", "Deadouchanho", "Johnuh dmon", "Finerroweh", "deaduank", "Johnord", "Makaukiy", "Sata Typ", "kaldeu Pnper", "Sundanso", "Ask amoslyel", "Doctummi", "arrooltzstor",
    "BennoNamttyp", "Pellahahflob", "Nucktardsula", "dansesty", "DrewapedCOPE", "salietaster", "Miraeaxnvito", "easteNoinetm", "Makrage", "Nognatrim", "Franarlo", "Lopreef", "Leonkado", "Fulld Toryan", "koraerocaken",
    "amorrisc", "kamoazGa", "daniarloielh", "Junklegi", "YesIhedeis", "INDI", "gameatie", "Atomtskimole", "No Mharl", "Rootigmalosi", "Nigmchiloeni", "amanuizt", "Red Vonnen", "Sladuan anpo", "andrboiw",
    "Reapummedgro", "davilladris", "guerivio", "Eckaempl", "Harol Rat", "ASIAblen", "Sinserne", "JanFametrosc", "Hedoicep", "Trollecttero", "Deatumpy", "Famealle", "aramawan", "Quacissrutyu", "Parkorsakejo",
    "Aforlisn", "boom vinota", "IM Tuxoraggy", "Happp", "Sbrooidm", "Aguivece", "Contearaleta", "DanRoda", "Embenoos", "DeniirWe", "chinoga", "Arifren", "Theoanic", "Ordeobi Bliph", "htonitol",
    "nicorachvels", "PARAones", "Yan hoco", "Phanlukende", "diegax", "TheCslan", "sappryst", "Leereydecsc", "hunttrik", "Spacroze", "Juuaornsnya", "Il Semer", "CladirBoenth", "milaancim El", "GATO nonym",
    "EntElpha", "wardel", "Nonougimdah", "acopikon", "Geraazelwald", "Rinknich", "Lazze", "leemnal", "Prua pim", "Visoazinuble", "alacanym", "kolomadyeBur", "Corokywa", "Yuichawnasg", "penwidne",
    "leliecteebre", "SkooSIAN", "leonbretonda", "Cainmand", "Takaakknbvil", "Omegikitster", "wadaemarlly", "asbrudzeadco", "klauaintdeyc", "eeliades", "Maromaqu", "YoDavez", "EmerrejaADEX", "nonxartoreya", "manklveeami",
    "yoob", "vinktach", "Infeopod", "Arthreen", "Slimllum", "The ohem", "Alliirescape", "Gwensund", "Dakioly anta", "Mildreenr Du", "cubatom", "ZauboctoePie", "orinukergBro", "Dann", "nicoired",
    "Petece", "Zhekopis", "lugikymennos", "IvanWESO", "Xaxoiga", "Sir exulnk M", "kostonst", "Visisnar", "Tannesudxlle", "soraupermeru", "Trozceic", "dkraranc", "Plaserra", "vinjuradning", "Skurlfa",
    "Savaashi", "Prim", "FillheILftor", "Maxxo", "AntiitDo", "vladye D", "Bottabbi", "Kapalex", "brunZeus", "chenWeek", "Saworock", "Lummoul", "Yellsmil", "GiansiaGck", "Panaimon",
    "expeaks", "Yuraarsincie", "Samsorefcieh", "Pheep", "alexabok", "Dirt", "Pyrgasso", "antpario", "swapapeTscor", "blacld Momic", "Famel Pasuidi", "eragexTh", "Omegdinpdret", "Akasamanarkg", "Glinanze",
    "FaoliRekxuli", "sergydrais", "cancndre", "alekasumeBea", "kohnye", "Underaximare", "Sorrredvisc", "tatluraS", "galuevot", "ArtiuckM", "chinaran", "MaDoorac", "Jorv ENIN", "Smugaxfa", "Taremans",
    "Mulkredoferm", "Rylsandrvely", "zanyslaybiko", "Smerrusaoder", "Arcachar", "oleghost", "DlesRAND", "Divepathssy", "artmhambEZY", "Ahgakmarazin", "AroVoisertic", "LeskoiTe", "Pixiobraotud", "KubIukah", "ArkyI",
    "Trucordt", "extelad", "Shinrex", "EnzouroSex B", "ZajemThaogun", "Ceikni Gnuka", "EmoteonD", "SkyHeanm", "Atlaastoat", "YesInfellone", "ilusattl", "danborqulse", "Gucihjunmx", "Giggsych", "Devoizel",
    "SweeocoBxx", "adveesse", "EcPchas", "YuukimuryHer", "The ankamski", "Grototre", "kespliveozer", "YastabieanSZ", "snaplasmnera", "AoShou u", "shahaptamdem", "Willbsolmerl", "Calvigelliko", "Lyzeumin", "Rourmaru",
    "alexalovrmes", "SleratliBard", "nexoon", "Ezekvanarito", "SanshePlid", "OneFerinbrie", "Kirpradewin", "eduholys", "Spikchal", "Crazaske", "DanyRedsppy", "LeGoomat", "Noboipos", "lordubin", "Zonaelip",
    "treaheRa", "Ambuottoueka", "ellikash", "Eye alew", "efeknfer", "Osirrthuie", "Swaiabu", "BlacospitGib", "Nardegab", "Affloara", "Jukeomey", "yindonzotEff", "LeBrroloin", "SaLoriel", "Legihikr",
    "Saddacha", "TheNaravuckn", "Balirestng", "Alemredratc", "Sageoriw", "erasonnoestr", "Silvndleetap", "Fancieud", "Aswoeorgst", "Typiickl", "Amikika", "Yusuroggodel", "Azmoatatraqu", "Kitsgand", "Yokadondrost",
    "FazelphaiKat", "Manaunnerxas", "olesola", "eusplyin", "Adepunnymi", "Acidrthugodi", "Wodzigus", "Deraokuhchon", "leobarle", "Somemjohzuro", "Harrasky", "Ojoxbbit", "Malaoaho", "Shamira", "Lendelikmbs",
    "Holyesonobie", "isiKeicc", "HeroitsiThe", "Vermlackkine", "Franldo", "IkkuaLok", "Georhite", "kyleoZor", "Elreitri", "Anotenise Cre", "yavgark imon", "PeFranic", "Reddrroo", "HATChesanzol", "Psycssak",
    "Haudalaxumbu", "lolioLeKrate", "Erasekoz", "SpicuanoyFhi", "kiriaptaRbIs", "Asteingykeju", "clouendr", "kespesmo", "catrarth", "Danyoukaruka", "funkornalica", "Lamesuu", "Heaveand EMEN", "Paulnsan", "Not rove",
    "Garbini rhed", "Freetom", "alexaedo", "whitarte", "Ashbndur", "JaiialeI", "Misuomzxsiel", "Argoigma", "Rohihe", "whytindy", "Vaniunna", "enryufloFISK", "Casthamo", "arthuLBaexan", "Aldoeekz",
    "Loulodri", "Holzsuhlmer", "Martaj Lutoc", "Scothera", "CdaMechbcus", "Dankolwaicak", "Salaztjachec", "Supeamer", "HaizazyPnkee", "Filsorkrmun", "Magntobonqui", "LokourDeusys", "Toilpaffposi", "Nostvigmrann", "cerdonas",
    "Geratis", "KypsenjieSom", "Propdam", "sexymits", "Zachuta", "Sailpathrkus", "Lalammo", "Maunerli", "Wolfroll", "TornhifreXer", "yokuickakill", "Goodord", "Bearemin", "Dorahado", "Beaootk",
    "Jazz", "Monoirgo", "Etnaery", "Tumbtololrus", "CapNarja", "Paiwendr", "Igorussi", "Cheshcap", "fajender", "CupCuronnwit", "Tigeilen", "emogarkisht", "Tedearkage", "Emdoicou", "Jestirtdommu",
    "Pipoenro", "stinamplstup", "Papaarco", "Fabiearb", "Malarma", "Polielik", "Greenowcu", "fellaias", "Donpasoneinc", "chalealPneri", "Anciuh", "Tyrrotsa", "Yoriavidux", "Zeseiss", "Cakeo Haxmanu",
    "Naczooha", "Undeinot", "uradameErten", "oatsimondus", "Wurmhibikamt", "Jadehaga", "Masyoble", "Graxanuungok", "luthizipon", "Tyraoude", "Yurahe", "Fergadij", "Fireel", "Ashtyric", "Opasei",
    "themlone", "Kirbnthoe", "MackPupoitzy", "Reimashertik", "Arrrarce", "Saraunth", "Harmelixiser", "Poologo", "Abelmyjm", "Jestheli", "Desuvery", "The lueb", "Zeksadma", "iSeaero", "AlidamcmiX",
    "Apfetoto", "Stateno ffei", "Onuralen", "israoote", "Helle Hi", "Ashelexk", "Nikoarma", "insijvenkolo", "Kintasyp", "Afroalmalede", "oscaucas", "oatsroxi", "Avalot Sedan", "Nazunory", "Shidomnu Di",
    "Humah Puyali", "Mugia C", "Capts Ezpple", "Steatarsinbo", "TheWerpydaBa", "hacksbra", "Enaiaide", "Son nyoue Ve", "IcedagegrGom", "YANTgrie", "Shadonovtryb", "iForeHonille", "Orbiahan", "Anujracl", "maxfinomotty",
    "Andeemmitrix", "DrahsGammwis", "Psaiunnyrshi", "Kingentoalos", "Missendo", "Scarnlym", "Lawra", "Slipunarfon", "Atendam", "dextaile", "Shazuno cann", "rafalect", "Dartombi", "Mejiwoortim", "BeamNOVA",
    "Rovevan", "kirtlime", "Jacsteq", "FUNTE", "Carloma", "Ghosiclaeloz", "Marccaruzeli", "Chesremis", "Hesuldor", "Lurvallsncan", "Alvaucch", "Alcrpfel", "Deroddie", "Ryneamue", "Facelper",
    "Bacoodne", "Copyduar", "Charcorpther", "SeiMoineycho", "Zaubkumadara", "Sergobal", "Scotubik", "Straavagamzz", "Virangel", "allamerf", "drubelph", "Arnonovetsik", "SpirFurvey", "Armaersi", "Nicoillp",
    "connongwerub", "Pokeincedanc", "Mistanryyeki", "Mordotm", "Sophigaba", "Lovano", "Shruavey", "Havoiniaeznu", "Tesieped", "Deatuto", "Zancot Kage", "TiagrMopy", "MaDomari", "Sisaicol", "yohbufei",
    "Hamlania", "Taseystoostv", "Oficille", "etcuolhanus", "Farmisak", "Monqanieenti", "Shadacemdori", "Nairobseyage", "jurzildr", "Morgollonz", "fredendy", "Truer de", "DJ Schor Tinh", "Matilets", "SiBaiktoimat",
    "Overrazo", "SpiroHax", "rhillfaf", "abraugus", "kingombisind", "lilkootb", "GoGaouis", "Codaduzh", "Axpeanieecau", "TexnlexPZAP", "Maltlche", "hasenodyazy", "drekrick", "abiginkuch", "Anhoafu",
    "takoffic", "Ofrarona", "Mickoblo", "Beasulogcher", "Minirixbchul", "Berlroga", "Cripara", "Brodndga", "Baloadco", "Aryahe D", "anthaharinor", "vlasineanwit", "LofnneArlaxe", "alpeutty", "yuut",
    "volbiduk", "izananizylit", "lpharyan", "One mithndol", "Balbampy", "yesyreat", "Axelndervima", "Animocalslow", "Vectylorning", "Yom uci", "Godhonza", "Azeivent", "mcnaojoexfl", "Johnrcelesom", "Coldrazo",
    "Jaad", "Crazljam", "ivanustu", "Killames", "Amplugseeyed", "Beanarry", "ArtNasy", "PREC", "Yochovaepisp", "KaTrugus", "Cesadrel", "Zornder", "mangslasviou", "cauderne", "Yugiumjo",
    "Jianateu", "farondre", "Calyltar", "Danti", "pauloshugers", "GonzuliuX", "Vivironz", "Owlilare", "Jotao", "flesree", "karkumse", "yanmartm", "Farmfir", "Exprt", "Vostshad",
    "Omoplend", "Marcenko", "Iriuhdgu", "Flarre", "Romm", "Risick", "Giriig", "Bbann", "josmama", "ProchePiach", "Stonleriohac", "Darkhe G", "LoXTont", "AsciupilBad", "Yaldoliifra",
    "Captazesho", "Zarristatus", "yvohdrel", "Sweervil", "Tobiyplolepo", "AnakalyfCASI", "JiCuroca", "PikaukKorape", "ozanael", "Joshenge", "AUGNitro", "Jeinoruauci", "Pracubannned", "kolyetrerrio", "Albeayra",
    "LoXiopeg", "Le Opark", "Guroiles", "Woroourathia", "Occuerry", "Akumord", "Aorrelta", "Jadeosielind", "Ace ubbe", "azumonut", "bonstsDa", "VectheDeuish", "Chinitbrmu", "muitello", "frozutis",
    "oscaaple", "Fillnclemazz", "milekumurlag", "jaliu telami", "Fisuorreafpa", "orseorev", "chaslineetom", "Yulouche", "only gho", "Shnalbas", "boopnderokan", "murindex", "SydoilaArius", "damiade", "Mercsimb",
    "Majokkuhtes", "Gnomhiag", "kysaatja", "JoseaAzu", "MyheZAK", "Antimberobar", "Senpanst", "Lilialco", "Sash", "Amrieta", "Dukoorek Mus", "Snowhogu", "Alukantomwis", "Shakstleli", "Papiroithida",
    "Amerumbl", "AnwianzaeZed", "Pilurozd", "Elawjet", "MikoI", "Jim", "Loreossj", "haxuez", "Lakkatri", "Erebil Mage", "PernSLAN", "jollanve", "letoniwy", "Dropanweames", "geeplSal",
    "TheLaze", "CybediBauser", "Helyndressia", "Kinglodzen", "Ichorigl", "Gromeni", "Dennoged", "Darkaas", "Pelorien", "Denezrai", "mariamka", "Jeffeste", "Czarlenirtin", "Razuaste", "mrjoekka",
    "Nomeanushnny", "PsycobokNico", "Treeenri", "Ixyrlextdy", "Markovetstei", "Kotoettr", "Addievenple", "mastatsuyHer", "viviathm", "kaitostocky", "roboiracon", "Alvihiag", "Xentarec", "MILE", "Boriost",
    "Derki", "gouierin", "yokouan", "kentuxor", "androefa", "Fandoker", "Zalaolku", "OmyZarry", "MyBaokem", "Igelmuny", "LORDotaku", "jujuva", "Goodaxbi", "Jefrruonii", "Mirtplo",
    "Cookasad", "Sillites", "Bradnurbibig", "Desuon Iarst", "Kaszzeinikes", "santonho", "Tuchelodlaes", "Kuriozze", "Bojahe", "chowassm", "Goldoren ACON", "Cladoodm", "Linelasimrad", "lucacemambie", "lenoong",
    "Erinilliic", "Hanshoma", "autireen", "Echoill", "andrsereito", "Blacsafi", "Braiwasm", "Randutca", "quirussa", "Lckyanil", "Huaahmetyson", "analonasterm", "Lummicolow", "Czariloo", "Iriuris",
    "Flylatoresde", "Sir emer", "Marydeektepo", "Nammzaze", "Evilainbrael", "YesIryceplay", "mikerigiazon", "Shamarlolt", "Dunnike", "salmaYum", "Wolfrist", "Toffursikoff", "KeisitCajolr", "Caprcapa", "Rosepple",
    "yurie Qu", "ricoynam", "Kumiwl Jhoo", "Jazeocknssy", "Sereeosz", "Osfaus", "Bubbead", "Calaga", "Deasraxigor", "Gaitamahmavu", "valloodlitt", "Lyzerrow", "GRONE", "Franfonsredg", "Kaspery",
    "Iwanasounty", "Ottoreo", "Mattilesl Mo", "Martskas", "Mistbdul", "Brosovkoline", "Afflgork", "Savihonbo Fro", "Buttorig", "Shitespa", "Stewoseilber", "Stathe D", "Raaiormiokie", "morearecerat", "Sambana",
    "ajprovae", "Gabrybor", "Joaoras", "Raptin", "Coroiki", "Barnelli", "Askeold", "VOLCEO", "Cesaogod", "Uchiixel", "Vincop", "toniteph", "ebouiahkutt", "faioazimman", "isajthanry",
    "guildzel", "Vastsa", "dimach", "lukylladdrog", "Stijarma", "Tensopsa", "lagmgame", "elieriedrche", "LIKEO", "BattAnes", "VieTed", "Grifoyga", "Loreeinillse", "Yukiack", "DeivheWa",
    "Cool am", "Bombache", "Diruamra", "Ainssamb", "Reorunurel", "RanLamor", "Akugunery", "Poliaris", "SaloANDO", "Auraord", "Georrich", "Ironmbersmin", "Lanchite", "Nesp", "Aviondy",
    "Gilveow", "Pycamarm", "Poioosh", "Mindemya", "Toksslan", "Platronieytu", "LogaOJIO", "Maneucio", "indeickl", "Arasmmy", "Josenais", "Poblrollmmy", "xXZaraeroXx", "deadokem", "Arekot",
    "Trolatty", "Demo Am", "Mentann", "GongnBruke", "HeyIekaaom", "PokeoTork", "Silemegu", "Zeusawn", "Lasahees", "Gyxeawli", "Aramark Hweys", "ZzeLco", "lordol walion", "kasnannn", "Matyenernaba",
    "MaeiheKi", "El Sorzi", "FireeeJa", "Mykealamkems", "RYT ricfinag", "Emdolsdynhor", "StonOT", "Kubuostm", "Derpatopkron", "XxsynalexX", "Chroedrichec", "Gabrhron", "Shiroladmyra", "Pastrait", "Mickreep",
    "alphind", "Yannnder", "Polieder", "Aviscli", "glacommy", "rezibann", "SupeQOQ", "supereeH", "MadPafav", "xVlalesx", "Kurtedre", "Enzonea", "Guigalin", "ChinlviteBai", "Cosmanny",
    "Yetkaxwi", "leileer", "Haylejecr", "AingbI", "Thoranek", "toroishaeaky", "Extrres", "Habeubudel", "Flaujiheaith", "echodasc", "Tapiooll", "Jere CAT", "Chogashi", "Keisintelcon", "Walsrimaom",
    "Tjokunbo", "FanTBoje", "artuuci", "zereinch", "ArcHanst", "Milkreds", "AterganduCar", "Rockorga", "Cripenki", "ToxigMo", "Absoojo", "Ryxcm Ke", "Mathtardvavl", "Videappyci", "Baselija",
    "Raaierwi", "Doglekofber", "Crymeibi", "anniikko", "Cookrazyviso", "Ripuisim", "Kindood", "Boyzarry", "finyhesi", "ConsSeal", "Kingmenf", "dnieocetni", "Arteroze", "Calvembonk", "LifertyD",
    "Shizaska", "CupCD", "andrimfo", "alsoexooite", "blubebsmnYde", "rorimOUT", "SajGrixisist", "Marmocommoy", "ZIPZOO", "Flaron", "Kundbdal", "SeptASSA", "Andyhinilave", "Trexchjeayhl", "Boreclipdaj",
    "TekMolonisy", "Loyau", "INemid", "Ebriiriuayar", "Semiivef", "NameooHowasa", "Pineerage", "DaBeonto", "Fontalva", "lioroefa", "Barbawre", "Domco", "Alz", "Gidasrome", "Manzole",
    "LinkR", "pincomTo", "Aridageftter", "Majaeeds", "HITLuaki", "kranylejnus", "Primecke", "Iskawant", "Ashebach", "Romairit", "Aephistin", "Blacrcuslyts", "Altetikyott", "IcyyustCecho", "Caculacktemi",
    "Swagakis", "Aritphonikra", "aarnabi", "Aweseyddayer", "Junrhadycamb", "Yalfentsu", "Logala", "Jabbinar", "SALTurse", "tramatryllup", "meltZacr", "bbtores", "rossrjosuebe", "Gabryata", "pifahado",
    "Realachibush", "Nautyeslrek", "Secouilpbegh", "banaigmaint", "Clowisca", "Bazyikol", "ferndalicarc", "Hideilol", "Killeno", "theRakim", "codyame loel", "Lafaitre", "uachbomirlor", "Matteignghto", "SHAR",
    "Dzotfrineen", "arlinsan", "chineila", "Zefook sz", "mariast", "AnImrin Zzer", "Elijabya", "ejayheLeOLCO", "Ririenoioph", "Fatiisch", "nissakiscole", "Angearedar", "Winsira", "Enyauenvgofa", "Crisshleckda",
    "Demoeall", "Rancingskali", "caazhannbpar", "Highucasavy", "Diabumpkkiel", "pongatra", "LudoocdiZARC", "ProAndel", "unbreofa", "Domiama", "ybdiermi", "valeakatgry", "Evynunay", "alphirMimos", "GunnlphaKatn",
    "UncligDa", "benoussi", "Lorducasa", "Stefuste", "pandLIO", "heldESIL", "Axiardwrefl", "EcarcoIs", "Ovidzufl", "YimSafxrry", "Headobleevor", "Basiizim", "Sabectov", "davilcha", "Retaaque",
    "Haizaini", "Killgrierro", "Hiddussi", "Alphovat", "Faceeu", "SergireMiopc", "Yuurumekughi", "kanearl", "FreavilTato", "Inesesynigop", "jokaarsa", "Deadudra", "Sandethalfet", "defeobal", "DanGrade",
    "Kaeleli", "iduzIndo", "Adamrex", "Wilsiorzgris", "xDynubkoozak", "Red andre", "Redoeviafear", "viakngelexyd", "Gundish", "Rainuluz Ar", "omegncle", "sleeanto", "Gearriye", "Darvural", "Catnaladx",
    "Darkac", "Olymdo", "Ranzupil", "Monoadus", "AluchadPota", "Rohianguti", "Kellpico", "Handuss", "Mememig", "Xurooksz", "Artorkarf", "AzgrI", "bagnsukatinh", "DoctarenDAC", "Jaceunatl",
    "Dregoraure", "Brobaitmtist", "Backncle", "Cariogi", "Malaanya", "Lordakiikura", "amaryBad", "Melvubyugla", "Riskhoen", "Cataanni", "Mindaca", "Plokimypiarc", "UnicaotiRAMO", "Ghosdriaeipn", "Noahulio",
    "meltrimm", "Dannfernail", "Victl", "Kaseydci", "Warcnfir", "thodoxyTriou", "Fattquigime", "Sodohleb", "werdsgei", "wedilmis", "Reepolannpai", "Nonoliogela", "Infeersidrei", "matoVES", "Deltandyaria",
    "Treelkav", "KvaKnottamon", "Zettooki", "GALASAR", "Flauohn", "Mayoiche", "Lewiyzbembur", "Amonkanalon", "Rambladi", "Tangoops", "Gearoxy", "Noelagno", "Junylamm", "Xuthrawl", "Lizaeowufos",
    "AleCateg", "TuJuventreyl", "Suzyempl", "Mildhe", "Missuestiara", "mengThinoque", "szosacon", "ericegibnJee", "Riwsornu", "Jacob", "dudumerilefo", "Arioima", "Deveu", "Semancy", "Boyiezey",
    "Awejadami", "Sisarasc", "Siralexd", "Sigmh", "CronThat", "haleewad", "mizieno", "Jellaserng", "Ninjajarsyse", "marsoich", "Navybbadiled", "Yamiikitomic", "Epicdsta", "john", "quitekre",
    "ARMYadar", "Yingdwin", "jockrigober", "Dieghe", "Chesni", "Nigm", "Joubliath", "Vortokid", "Mongpo", "TheLhomp", "Undeakon", "Ganeenaj", "NewRead", "Bokoelax", "Speeayongu",
    "tashATO", "Lukeelet", "IvatOLDE", "Remzappe Smi", "XxMoayMoxX", "Exotighisrix", "Primshio", "stonriti", "Rystastamass", "KitKayleeito", "Basiainemily", "RockolhaYPT", "Fierneestogo", "AskaheOrgeCa", "Zapaulia",
    "AmanlyDu", "Chroalamnqui", "KingceCr", "Scraohitvins", "ScubomanrgHo", "curtackTboon", "SergodTotron", "Hiarebsm", "Gevercad", "Anjiabrialin", "abarenz", "karehincci", "GoldKON", "Haharkim", "drozajni",
    "Riokiiar", "ROE ANES", "Endesaac", "Methiuli", "clinanan", "itaylack", "Indeatsunzy", "Kooprocke", "Loboansadari", "El Sizzm", "daviastevva", "Rustezio", "Stewepedtrin", "Ziillejiha", "MaYeurtl",
    "Pyroiggy", "Cham", "Luxura", "RAME", "werilche", "Terrob", "gazesdoildre", "Bropugo", "Tartinchmmie", "Xileadne", "lufeikeanla", "Fleuittl", "Codeamararam", "iliaincero", "Krisuper",
    "Summrisondor", "Cesae", "Karmextrnar", "elsuermi", "levihe Fio", "Waldrago", "Palaihirnner", "Dallnonitatn", "Kaneastezfia", "Angeionpeen", "olakidie", "halnogus", "Yopk", "jellhayord", "Sickariohito",
    "Nobounagndos", "kaicxel", "Sifehuisntig", "zsewordn", "MuSuKageory", "astrroom", "Kennabbe", "sidnhaggtila", "TheIommo", "kaziecto", "yslaordi", "Sanducaske", "aitainja", "Eskaj Khkis", "HunWrimsllon",
    "Incaakie", "Kiialexi", "pandpeedlami", "muleobbe", "saurnime", "vitoick", "Alfiinyx", "Mewseichfrez", "anneresh", "Webborbivonn", "ElMulivissya", "jojoshid", "SkubhtervinA", "Raptlendvizo", "The aiom Mos",
    "gouikottmany", "garceoLe", "ATGRmagi", "WandasuaPTY", "Kataatha", "linnshap", "azraessaokan", "Judie ja", "VoLKpard", "Aleatijnnis", "Aimnhebi", "Pharamesooky", "gg morzickMi", "Gunbamon", "LordoFre",
    "Sqwuoren", "vldiudee", "Sentocto", "Picaogudince", "yetkrFah", "Greeeichgnon", "Mnveojatgry", "Adamenenyzie", "Erencratmett", "hugorlav", "rayparalihac", "someierrmita", "Netowtaocs", "edwaingVofac", "ARMKrail",
    "Funndd S", "moraagot", "Samwonpalfor", "Bacoaro", "Mophanzi", "Sameawre", "Baropace", "Waddlabudie", "loseoine", "Rinkhestriso", "IDM ynea", "Firejunj", "Uchiddieake", "Wiyuir", "Borois",
    "Bonqol", "Quancio", "Kindui", "Ogampple", "Terrlausarke", "alejogna", "yancdhar", "AlexmpGu", "Sabeichs", "Jerexod", "Lubkhabb", "Ravoydarstor", "Overxperlar", "Martippe", "AdmikaInrice",
    "Karsxtra", "Johnunch", "Moosovyd", "Axiegore", "Zomaenio", "TengoCo", "LaxLunch", "Gaymhiroanto", "Oranypic", "IamJenk", "jannerteziak", "OkimvynH", "AvikakkorXma", "Jacoypow", "Bacoalaxti",
    "GodRil", "Aystegsfia", "maniapit", "Lostiguelode", "Haruaum", "MrMuul", "SupeFreester", "Evilran", "Righog", "Alexhrislta", "Ash iang", "Nikoolznosty", "Leonelornip", "Extrnner", "AlfioresNA",
    "Gogoomad", "Jedaarabpiva", "cheraqer", "Yuicrosj", "Mighrenc", "Beckbaa", "Crazree", "Skraanni", "Scrumpo", "Putrhomp", "Krita", "Raugeste", "Roldvyno", "GrotejaMivdy", "EksearryPixe",
    "fradmletist", "AdySosha", "Eitaargintis", "lolsanat", "Arcohibi", "arudndre", "Jokanipeseli", "NearYAT", "Arizasia", "LassleoluriH", "Lufearosrito", "bielRATO", "FuzzOLD", "Sainndig", "NARU",
    "Enaionk", "zizaontemnul", "Skycnowh", "Martreat", "NICO erren", "Venuics", "MEAT rich", "pyrookerlatr", "Snipeape", "Dyenritz", "Wolflex", "diogorvm", "elcouanx", "Adoreisslara", "Awakiber",
    "Dubsquid", "Pyrggois", "Poolurkachol", "Kevellio", "Spagshio", "DrMoirco", "RedSly", "Metalause", "Yaldudeb", "Pyrgindr", "Belmry p", "Nevebannxy", "kuripell", "Bossnsil", "Ole ripaki",
    "Combarpo", "Ryhiot K", "Yegoilso", "Voxirae", "edisseal", "Kekeicahtik", "FacepTashe", "Gameatarmbie", "Tritiniuied", "Valaikkurol", "Jhonbdie", "Adaiaven", "Trexonk", "TobienOm", "Fierimmy",
    "Adibramedead", "Kitsezoo", "rollanch", "Urarwyntrel", "iliauins", "Duckononptai", "Tronondo", "aital pirane", "Minserpy", "ilcaipe", "derplexnnor", "MariucklTon", "Iskaotmu", "Rickersttato", "Pussarosue",
    "Hopeluhi", "Tazluncadas", "GG Iarcu", "Luckmand", "Rubelfourror", "Hakazibaving", "coltor", "Jamnux", "ZetlioOrazy", "Nafuelta", "Aquilo", "SoSail", "Zaizukacola", "Bennrbal", "Biznvolvg Br",
    "Kuroordoealb", "Shownfam", "korbotet", "FBTeazlohoco", "Univapym", "Compome IKAU", "Aumeythilact", "Lazybbat", "tomaick gein", "Variednorgot", "davilimb", "Saltode", "hexxashe", "TheRorollo", "Mathronmnati",
    "gg aoelen", "Catti", "Janurall", "Killyree", "Franylpy", "OneTaize", "Eviloly", "JelliCur", "Ogamavak", "Kiriasle", "Drugvah", "Capeirim", "Dilaoaomam", "keKeovieker", "Catammem",
    "Wachotat", "saliedno", "Zombielo", "Ovidlimi", "ShinduarJuas", "Doesortu", "VyseUNTE", "Placanka", "Nikiatiscarb", "KapparBi", "diegnee", "BooHoung", "Ray ltar", "Necraveyl", "Pokeark Matiu",
    "Toucietz", "Oogihe", "PaulrWetresi", "Zteveero", "Lokobto", "Mageeman", "Brocuritele", "Mittecynckso", "Jadehemo", "Gameuh D", "Shupagik", "Mindaki", "AngekorMbman", "arahoili", "maliamDuaken",
    "fernekinampf", "Gammlabulazo", "Carlfra", "jeffyzze", "rahimoto Nam", "Romahoen", "Matteginron", "Persfirh", "Garrarto", "Bald Boomer", "Megaute", "Ruanlten", "Jererisknami", "Abelikiw", "Tisceeco",
    "Reddlvasvaro", "Darkegat", "Aegindy", "Darknifi", "Potwacazmon", "Atomondo", "Exhaike", "Yexelueb", "Draha", "Bibohado", "TheZaBig", "Jazptray", "Xonorza", "Maloomasiele", "Grinockeomal",
    "Gorumrra", "Joimrkan", "Darartayter", "Chibreys", "Toryhepoesom", "Mirteadl", "NiriAVID", "Uranjpre", "Dennuyufishn", "Unluhomante", "Pipeanebguia", "Vileoreseinc", "Excelphavis", "Replideembo", "Araclauc",
    "ItsYushegies", "Peeketkakora", "Lyalzaze", "Pornetre", "Youroci", "Entrhali", "Potanabb", "Lunapplector", "ahmerror", "Aledquidusys", "uniohemuders", "Starraft", "Turtatlangya", "Oragand", "JoshuaBR",
    "Proftomi", "MeowGK", "Ramb", "Estaacif", "Paulatur", "Unicuicates", "Papainix", "MonaipLenjoj", "Waldonalas", "Neveatabasto", "Rubbord", "FirultraNoir", "Shabinslusad", "Marcustyary", "USTadam",
    "Rukuartileli", "Cladappe", "Gabraped", "RexaonateBea", "FixmetBlughi", "Mikoamdaeki", "Dullkorp", "Togameenuk", "Temimagi", "AkanNEKA", "Bad canlo", "diedFar", "RareOgr", "Synsideddy", "Karnozyiago",
    "Aveiulka", "Remznhon", "Xantinit", "MainordPork", "Arcliszt", "Mainlive", "Wuioide", "Pylomorizbaz", "MyBalect", "Deteorde", "Captovig", "Poblhish", "Xerodsti", "Panonzakoca", "Flyloncz",
    "BogaGord", "Nortndrethal", "NatsacPr", "Godoiste", "KaMoaven", "HeXute", "Gabrheep", "Mimosych", "Thiandre", "Eleceroolam", "VermIDEM", "Albir", "AwakNEKA", "DImKrain", "MrWeinscsual",
    "alexelix", "mojtemp", "Tiloakasasha", "Alonael", "MrMuark", "TeUMU", "Spacrt", "Corehou", "Elkahyeazipf", "Unrecsid", "Albaoki", "Farmustakbro", "METAmazuban", "rossilkw", "zmannyFherat",
    "MeltaendHaz", "zhoulods", "martborymsam", "Bropomah", "edvikainifl", "Sinpalde", "Ameresde", "RanLekoz", "GeeGlweirou", "MaYenimarica", "lukiwais", "Askuunte", "MajoupOf", "yunuasypven", "SNYPesti",
    "Doisobaldrew", "Luxandobad", "NakVADD", "Amura", "YazGgentke", "Otarammyen", "Dullimese", "RandeyLa", "Atlaeallusto", "Loboegapimci", "MURMulta", "yukiainieLop", "austisur", "LostheZeckso", "astoybetzzan",
    "Net carr", "TUMN ifre", "ImBudd", "Sirazy", "Negrvili", "TalecePulko", "Syncsaac", "Baepurga", "Zvinabizrgon", "Oshiepaguncy", "eusiicto", "Kokyia Cckso", "War Meter", "Rosiybandrog", "Mikeandord",
    "Gameushe", "Squaou Knel", "Lawrabeleave", "Birdendeking", "Otectran", "Elle", "Napsddic", "Uchydent", "roryamah", "RexanjimeKub", "Levuolco", "natiosuk", "martarlo", "TheNopt", "Crowurio",
    "Assarasbacul", "Sparende", "celeigheaumz", "slavicou", "Adysedos", "kiervivs", "Bubuiine Nam", "Yokihind", "nataermi", "Frosero", "greearap", "Thaturn", "Mileoike", "SmitajtVatya", "raphlJef",
    "Siendria", "MacPunnyliva", "Karkferitoua", "Maksobbl", "Glau Conpav", "eliaat C", "Gameang", "zippatxe", "Mildamfi", "maligsse", "Rubyathuleus", "AveienhoTE", "Elinight", "Doppashmick", "Smetafak",
    "YaniNeedari", "Aumpyichi", "Aumpykos", "Rylshort", "papaya", "Faderady", "Nautiktoilen", "Makkrsene", "Aestasii", "Nelphion", "Hukina", "Lizard Man", "Polimo", "Azeal", "Wizzy",
    "Charles", "Eliza", "Walrman", "Spraenno", "Henkombe", "Lumiszat", "Wachothame", "Sir osto", "Matimoj", "BelkelabName", "JagsayDorret", "Lazyilvo", "Tyraazzd", "Senporis", "Kuruebuo",
    "Zararif", "Cracik", "Nandosmi", "Pinkiankas", "Happinjatsho", "Fibem", "Plach", "Doct borgget", "Joe QUAN", "Rat", "GunSinal", "NewRimolpera", "Tiscibit", "Avoxlwoo", "Gucciger",
    "Kachexy teg", "NewteLacneso", "Otreutcaot", "moerania", "Chroll", "squamer", "Rafarespo", "Ralyaikardu", "Spoen Om", "Pumperic", "Haularonilla", "Lasaruruhab", "Jaydarvaoyli", "Ugotarcoster", "Omoporth",
    "Kowaneakredi", "Hawk", "xNiczx", "ROMAesti", "Holfentebi", "Onin", "mcberish", "Mageolbr", "Gunbhakerail", "Only a ejay", "Floroshubody", "Esteovje", "the omat", "Matterp", "Yurahitakyo",
    "onreNHEG", "Slenulp", "Andyaght", "Frangien Ju", "Kappa", "Lossmy", "Oztroroni", "Kafuucky", "Suthoo", "Solononysy", "Tigearce", "Fallomme", "Zemerago", "Captawze", "Dextakii",
    "Supewen", "Raymrosi", "Thatwa", "Draglean", "Amiretz", "angissau", "lonerebrllou", "Tairyosshuff", "Homerist", "The urel", "DietPOH", "razokiss", "Pedrenilti", "Uchipoll", "DexsiliPenio",
    "SouvzMoncus", "Mordastr", "Meduicia", "Alphnvel", "Enveagmaikur", "IronorteTORO", "sadouspe", "gamiltra", "Swerr", "Anotrigo", "Cellabi", "Meorevmily", "Makuurpl", "Andrrusyrani", "Alekamer",
    "Makuentlnent", "Hardesmodena", "Epicholzi l", "Sqwuybet", "Sinpoxic", "Pycielo", "Joreumbauter", "Kamlag", "Egyprazynceg", "Evilrizzonto", "Roshezyr", "Marcucka", "Hqing", "Red dumbo", "Granrick",
    "ShaLewge", "Justlbaturdo", "Trivasic", "Micherra", "Zhekrosj", "Pandiuli", "Avilroko", "Carsinis", "Anteeity", "Sawcaul", "Unknvinx", "Matiukor", "Varamega", "Holzewto", "Monqarfi",
    "MrLuick", "Jonkaktuaos", "Lostever", "Mikeepcilami", "El Sjarn", "Drryk", "Dropsian", "Sodaerem", "Phoeucuost", "Lautatt", "Nesseril", "EvolavilI", "Macoario", "Suaroxaiceap", "Genezloptsun",
    "MrSeeroi", "Mentcridsena", "Luckrake", "Zahomacd", "Gwehltlitnap", "Banaoyal", "Agogreenbywo", "Novaunglriov", "HaoKbobo", "Afroumeg", "Ukaiarkcdiak", "Reydicva", "Yuukirmi", "Pinglejo", "Sageetylmtar",
    "Tykaslumavea", "Lemozost", "Skasomig", "Victanikath", "Ironendrtana", "Brasaldrezti", "Japprozd", "Crowerrempsy", "Pineighertin", "La Goseirryq", "Rockizou L", "Nosaippi", "Eridoina", "Cawfuar", "AceAille",
    "Obvirmax", "edst ast", "Amonvall", "Amonlesh", "uFromithckel", "Tilootat", "BezpstrokiDi", "Daesal Blan", "BACOkerr", "OmegaPoggers", "Delkawrewurt", "StenessLnnym", "Yerrce", "Lorderyrkvo", "Kaloumiz",
    "AteraKao", "feneetahleta", "Shimenenvazq", "Sneaaine", "SupeAXOR", "reinarpo", "AdilheGo", "ChesainZ", "Saneolo tric", "Psyceept", "Dipoddie", "Lakmentae By", "Coukmoh", "Tortaras", "Voltarva",
    "Tacozadz", "Tera Litnith", "Krydruhanry", "Pondzadz", "Gosuasumerod", "Crazithv", "Raidantemble", "Baboob tkoro", "Adimelumnsle", "Presoker", "Deeplapm", "Boneo", "Remeuthe", "joanonocadow", "KarnaPro",
    "Iskarinaenox", "manidiva", "Tannevinunin", "Tommlmeceopu", "Holyuxap", "Warnonzieese", "BearilwaI", "Kanilide", "SpagREEN", "Infoheng", "Dannirisesel", "Avilenji", "Darkamioiz", "Ozitumatre", "TheLetBican",
    "Skabolkv", "Galaevee", "The obin", "Psycishtyali", "LabiesuCerre", "Sellerst", "Jellendr", "luckhazzragm", "Dangeejwath", "Airtnee", "BlacotLillou", "Jacknapi", "Azulctay", "zuzvisenzloy", "Jemeerna",
    "Renkuilhhlap", "Artyacob", "LazzndleaChI", "Why buglrt", "Jakereenhino", "Nicoikto", "BurdudeKenfa", "Vennraph", "ArtHnfin", "Quacili", "Nighhownrvis", "Astaama", "Hugounkytaba", "Michilipruze", "Traiyrod",
    "Lordaulnne", "LosBiguee Mi", "Joacombo", "Lucaroba", "AnnamBro", "Ouktleop", "Webbzmo", "GRAN", "Mozoane", "KeisMINH", "isaaunte", "Jamsalgrnda", "Darkarceshik", "zhenTAGA", "Aganred",
    "Miditernta", "Askaakat", "ZzLavirlker", "Maceomasdson", "Alysopelan", "Nyoicosvnton", "Jeanngel", "Kandugin", "benlteve", "Aragodnejeem", "Alacillilone", "Raufombi", "Lihiiroile", "laleilirate", "Joe livezYum",
    "Huskelal", "Ovegires", "Onlyltra", "AnthmyZanenp", "Spagswalllow", "Xunsagehmar", "WinkRYP", "Eitaiabl", "Baseecro", "Andringl", "Psycpartiboy", "Zecaidne", "SouIkohnltig", "FantnerGnate", "DragikaZ",
    "DaytinkMnkee", "Inliamertorr", "Profso", "LaMirocopot", "Zoioello", "Mikeancio", "Battelek", "Trexini", "Berizireoppe", "Blatnott", "Arparyst", "Zizounky", "Watcalba", "Tootinkovori", "Dessltra",
    "EthazzIfe", "Wookemanmoy", "Adonelbeliot", "InteunFe", "Storilonimo", "Ptituckytnoo", "Spyreadsspai", "Sky outh", "ChasoneRnoi", "Chanavy", "Daweapzeaniz", "Fandylefostl", "Dantxpermes", "DogeiscodPan", "Jeriicol",
    "Vostueen", "ferrennynath", "riveronragon", "HankNema", "Dartucif", "NewRordh", "Elecannonco", "Jonaipistdog", "Inseceri", "Spawump", "Heroankais", "CaptireInati", "Econanicnter", "Anoncapesmin", "Cactabba",
    "Toonockovvri", "Yajmucky", "servlvan", "Viqualgapha", "Justlf E", "Peddurry", "LENASH", "Korvitou", "Meyeorta", "Hasgat", "Ventyne", "Azraade", "Anomark", "Tortoj", "Bastners",
    "Paridilg", "Kuruabrileni", "Brayabulint", "Alphicol", "Nocilect", "Khoetenm", "YongmmaTanti", "SayoruTu", "Comjron", "DasBK", "Beboour", "Civiruth", "Endear", "Kirilydr", "Spriltur",
    "Luiznime", "Walaaprarsli", "Supeickd", "Goranc", "Skraomasrius", "Epicarku", "Techtudlmoth", "Jokoannycomi", "Hammedro", "Sexyrola", "Lanaauza", "Rabbapa", "Huaahans", "Genegadd", "Sherdria",
    "Mendlderther", "KoseKost", "Juss", "Dorahoot", "Adasreen", "Jeinougl", "Arthndyl", "Niceixt", "wynt", "Beboijamelho", "Leksnari", "Rushroco", "Cronack", "Oldmaz", "Zeusalai",
    "Zionncle", "Ninjax", "Sharulu", "Alanayma", "Ivatkult", "Wintxumo", "Darnukey", "babasi", "xixon", "Koleiriu", "Cleaoust", "Andyuren", "Gokuooff", "barrusak", "Dymclan",
    "Cocaroxi", "Paulmein", "Perionav", "xFauduar", "Paryumus", "TheCorde", "Straurde", "eduardo acle", "Stenceno", "JavoixxX", "Proionne", "Elixitsu", "Trapstro", "Zanlerbeunin", "Brunwirl",
    "Siridysrmon", "Steauchu", "Maymelta", "Akaremit", "Fredasina", "Minsandobero", "Arcteziheter", "DanZojat", "Garranberosa", "Jolleni", "Pastadesonbe", "DebiCole", "Czaramer", "Revaouch",
]